### ISSUE TITLE
Request for a new fonctionnality

### ISSUE THREAD

**Issue by th2j** [LMS-Community/plugin-Qobuz#73]
Hello

When i scan my qobuz library, the amount of album imported are lower than my favorites number
Some albums are not imported because they have disappeared from the qobuz catalog
This happens all the time, albums disappears and reappears with new id

Can you export the list of albums witch have not been found during scan to a log file please ?
It would be useful in order to put them back in favorites (manually)

Thanks
Thomas

**Comment by michaelherger** [comment]
If Qobuz doesn't tell me about the album they no longer have, how would I know about it? 😀

**Comment by th2j** [comment]
for each album id in favorites
if it exists in qobuz api, you import
if it doesn't exist, you put the id in a log file

**Comment by darrell-k** [comment]
I think the issue is that although when Qobuz move an album to a different ID it remains in the local LMS database until a refresh, when we run the refresh, we're taking the Qobuz data as canonical. 

The is possibly a way - saving a list of Qobuz albums in LMS before the refresh, then outputting to the log any which are no longer there after the refresh might work.

**Comment by th2j** [comment]
i think there is no need for that
because the albums who disappeared from qobuz catalog stays in the favorites list
they are listed in the favorites but they are not imported in LMS because when you ask the qobuz api, it says that they dosn't exist

**Comment by michaelherger** [comment]
Here's what LMS does:

* ask Qobuz for the list of favorites
* ask Qobuz for more information about the items listed in favourites (if needed)

So: if an album is in favourites, it should show up as expected. If it's no longer there because it doesn't exist, then we don't get anything. But there is no way to say "Qobuz, please give me information about that album you removed from the favourites", because it's gone. There's no reference to it any more.

**Comment by michaelherger** [comment]
But how would we get the "missing" file? Sure we do get the first list and could compare on a subsequent run. But how would we know what has been removed by whom? It could have been you removing things. It could have been them. We have no way to know.

**Comment by th2j** [comment]
i don't know exactly what the plugin is doing so i can't tell

but what i do manually is :
- export my favorites with soundiiz or with myqobuz (https://github.com/fdenivac/myqobuz)
- ask the api for each albums

if it exists i have the detailed informations,
for exemple :
http://www.qobuz.com/api.json/0.2/album/get?album_id=bavafij8nim9b&app_id=814460817

if it doesn't exists i have an error 404,
for exemple :
http://www.qobuz.com/api.json/0.2/album/get?album_id=wrqh7mdhay6nc&app_id=814460817

**Comment by michaelherger** [comment]
Please try to understand how the scanner works:

* we ask the API to return the list of albums _currently_ in your favourites list
* there's no other step, really

So there's no way to figure out "hey Qobuz, what did you decide to remove from the list?".

And no, I'm not going to keep historical data of your collection, to then try to figure out what you removed vs. what they might have removed. There simply is now solution to what you're asking for that I am aware of.
